### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by jshearon** [nss-evening-cohort-12/pants-overalls#1]
# User Story
As a user, when I first visit the site I will see a landing page with clothing categories and featured items. 

# AC
WHEN the user first visits the site
THEN I should see a landing page
AND there should be a site title
AND there should be a navbar
AND there should be a COVID-19 statement banner
AND there should be image links to category pages (mens, womens, etc)
AND there should be a row of featured item divs/cards
AND there should be a footer

# Dev Notes
The developer is expected to include the Site header, navbar, Covid banner and footer. These page elements are will be created in separate issues and will be linked here when created. 

There should be an empty #site-header container div on this page 
There should be an empty #navbar container div on this page. 

Covid banner will be a div spanning the width of the main container with a red background and white text. Text will be an `<h3>` sized element. Link to current Nashville reopening roadmap should be included in banner and it should link to https://www.asafenashville.org/wp-content/uploads/2020/04/Roadmap_For_Reopening_Nashville_Grid.pdf

Category image links should be in the order Women's, Men's, Children's. Each link should be flexbox row of cards with justify-content set to space-between. Each image should contain an appropriate model for the category. Each image should be captioned with the name of the category (i.e. Women's, etc). 

The featured items should also be a row of bootstrap flexbox cards containing 3 randomly selected objects from the #14 items array, one each of Women's, Men's and Children's, and include the item's image, title and price. Use printToDom function to print the cards to the #featured-items div. 

Category Image Links and Featured Items divs should be responsive, using flexbox-basis to set the item width. 

There should be an empty #footer container div on this page. Footer should be stuck to the bottom of page. 

![Screen Shot 2020-05-05 at 9 22 51 PM](https://user-images.githubusercontent.com/62916291/81133234-9def9c80-8f16-11ea-8ca4-0eb0affe1b95.png)

**Comment by luketlancaster** [comment]
What work would I, as a dev, be expected to do if you handed me this card? From what's here I assume it's everything on that wireframe, but then I notice there are cards for the nav and the footer too?

**Comment by luketlancaster** [comment]
so does
> Site Title - #3 - should be placed in #site-header container div


mean that this card will place what that card is doing in that div? Or that it will be placed in that div, and this card only needs to make the `#site-header` div for #3 to place things into? Same with all the other "should be placed" statements
