### ISSUE TITLE
Adult's Category Page

### ISSUE THREAD

**Issue by jshearon** [nss-evening-cohort-12/pants-overalls#10]
# User Story 
When the user clicks a women's category page link, they will be presented with a set of cards representing each item in the women's category. 

# AC
WHEN the user clicks the Adult's category link on any page
THEN the #container div should be reloaded with all item cards in the adults category pulled from the items array
THEN I should see the dropdown to sort the items by price
THEN I should see a collection of flexbox/bootstrap cards for each item in the category
THEN I should see an image, a title, a price and a link to the product specific page for each item. 

# Dev Notes
Item sort function is a separate issue 
Use bootstrap cards for item card design
Items will be iterated from array called items. Array called createCards will be used to loop through array and create html for cards, which will be printed to the page using the printToDom function. 

![Screen Shot 2020-05-05 at 9 14 45 PM](https://user-images.githubusercontent.com/62916291/81132892-924fa600-8f15-11ea-86ee-2e7df6616d4b.png)
![Screen Shot 2020-05-11 at 7 29 44 PM](https://user-images.githubusercontent.com/62916291/81625239-ecd97e00-93bd-11ea-9a21-f3cde1c94d7e.png)

```
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Cras justo odio</li>
    <li class="list-group-item">Dapibus ac facilisis in</li>
    <li class="list-group-item">Vestibulum at eros</li>
  </ul>
  <div class="card-body">
    <a href="#" class="card-link">Card link</a>
    <a href="#" class="card-link">Another link</a>
  </div>
</div>
```

**Comment by luketlancaster** [comment]
Is this it's own html page, or just a separate `printToDom` called somewhere?
