### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by jshearon** [nss-evening-cohort-12/pants-overalls#2]
# User Story
When I visit each page on the site, I should see a navigation bar with links to each page on the site.

# AC
WHEN the user visits a page on the site
THEN there should be a bootstrap navbar in the header
AND there should be a link for each page on the site

# Dev Notes

The NavBar should be placed in the #navbar div container on every html page

Pages that should appear in the navbar are 
<li>Adult's
<li>Kid's
<li>Cart
<li>About
<li>Contact Us

![Screen Shot 2020-05-07 at 7 02 05 PM](https://user-images.githubusercontent.com/62916291/81355885-6c510f80-9095-11ea-9c6d-136f37be0d7d.png)

```
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>
```

https://getbootstrap.com/docs/4.0/components/navbar/

**Comment by luketlancaster** [comment]
does the search do anything? What's in the dropdown? What are the nav links and where do they go?
