### ISSUE TITLE
Site Wide: Company Title

### ISSUE THREAD

**Issue by jshearon** [nss-evening-cohort-12/pants-overalls#3]
# User Story
When I visit each page on the site I should see the Company Name ("Cattywampus Overalls") in the Celestia web font. 

# AC
WHEN the user visits each page
THEN they should see the Company Name
AND it should be in the font Celestia
AND clicking on the company name should return the user to the landing page

# DEV NOTES
Use font Celestia for Cattywampus. Set text-decoration to none. Company title will be a link. Upon hover title text should change color. Clicking on the site title should return user to the landing page. Title should be centered. Use `<h1>` size tag for title. 

Title should go into div #title 

![Screen Shot 2020-05-05 at 7 39 24 PM](https://user-images.githubusercontent.com/62916291/81128888-261a7580-8f08-11ea-8336-c83877272b81.png)

**Comment by luketlancaster** [comment]
this needs clarity. I don't know how this is implemented? Like...do I go into each page and add this header?

**Comment by michaelclark2** [comment]
I'm kinda confused as to what this ticket is doing?  is this the same header for each page, or a different header for each page?  how is this different from the navbar?
