### ISSUE TITLE
About Us Page/Company Story

### ISSUE THREAD

**Issue by jshearon** [nss-evening-cohort-12/pants-overalls#6]
# User Story
As a user, I should see an about us page with the company story on it

# AC
WHEN the user navigates to the about us page
THEN I should see the title of "Our Company Story"
AND I should see a paragraph that contains the company story
AND I should see an image of the founder

# DEV NOTES
Image should be left justified with paragraph and text wrap

Page content is static and hard coded

Text will be provided. 

Refer to style guide (to be generated shortly) for styling guidelines. 

![Screen Shot 2020-05-05 at 7 59 31 PM](https://user-images.githubusercontent.com/62916291/81129772-151f3380-8f0b-11ea-970c-db118970869e.png)

**Comment by luketlancaster** [comment]
is this information hardcoded or dynamically generated? Example image? Any styling pointers?
