### ISSUE TITLE
Add Item to Cart

### ISSUE THREAD

**Issue by jshearon** [nss-evening-cohort-12/pants-overalls#7]
# User Story
As a user, when I am on an item page and want to order the item I will click on the quantity select box then on an "Add to Cart" button.

# AC 
WHEN the user wants to order an item
THEN I will first select the quantity via a dropdown selector
AND I will click on the "Add To Cart" button
AND I will see an alert that item has been added to cart

# Dev Notes
Dropdown and button should be bootstrap
Alert should be a dismissible jquery/bootstrap modal 

Items should be added from the #14 items array, into a javascript collection called "cart" with objects that look like:

```Javascript
{
itemId: unique number of item should match itemId from #14,
name: ---,
price: ---,
color: ---, //from selected color in form
size: ---//from selected size in form
}
```

![Screen Shot 2020-05-05 at 7 45 05 PM](https://user-images.githubusercontent.com/62916291/81131570-2c611f80-8f11-11ea-8cd2-88bbf4d65db9.png)
![Screen Shot 2020-05-05 at 8 43 22 PM](https://user-images.githubusercontent.com/62916291/81131574-2ec37980-8f11-11ea-9990-1c897af43992.png)

**Comment by luketlancaster** [comment]
does anything else happen when you add it to the cart? Is there a collection in your js that the thing gets added to? What gets added to it/what does it look like?
