### ISSUE TITLE
Product specific page

### ISSUE THREAD

**Issue by jshearon** [nss-evening-cohort-12/pants-overalls#8]
# User Story
As a user, when I click on an item from any other part of the site I will be taken to a page that lists details for a specific item. 

# AC
WHEN the user clicks on an item link
THEN I will be taken to a specific page for that item
AND I will see a title for the item
AND I will see an image of that item
AND I will see a description of that item
AND I will see a price for that item
AND I will see sizes for that item
AND I will see a quantity selector
AND I will see an add to cart button

# Dev Notes
Add to cart items (quantity selector and cart button) are on separate issue

Item information will be pulled from array called items in main.js based on an item id. The createItem function will create the div for item info. printToDom function will display the item. 

#14 items array objects should contain:

```Javascript 
{
itemId: unique number,
name: ---,
imageUrl: ---,
price: ---,
category: Womens, Mens, etc,
description: ---,
availableColors: [Blue, Yellow, Green], //colors are for example only
availableSizes: [Small, Medium, Large]
}
```

![Screen Shot 2020-05-05 at 8 54 12 PM](https://user-images.githubusercontent.com/62916291/81132044-b2319a80-8f12-11ea-8db9-eb497328191d.png)

**Comment by luketlancaster** [comment]
you should be able to link to the separate issue now, just so it's easier to grok the relationship

what does the `items` array look like? I assume it has some objects in it...but what should that object look like? Agree as a team about what you want that to be, and plop it in here so the person who works on this card knows. In fact it's probably worth it to break that out into it's own "made data" card or something. It's a small amount of work, but that way it can be done and everyone has access to it

**Comment by jshearon** [comment]
Decided to merge this into the cards on the category pages - a separate page for each item is not needed
